### ISSUE TITLE
Reproduce table 1

### ISSUE THREAD

**Issue by Haelles** [wyu97/GenRead#2]
Dear author,
&emsp; Thank you for your outstanding work! I would like to reproduce the experiments mentioned in Table 1. Can you please guide me on how to train DPR on the FEVER dataset? I noticed that the KILT knowledge source is vast, and the official repository does not provide the DPR checkpoint trained on KILT FEVER. 
&emsp; Besides, could you please tell me details about "Contriever + InstructGPT"? Did you just load the contriever checkpoint released by https://github.com/facebookresearch/contriever ? 
&emsp; Thank you in advance for your assistance.

**Comment by wyu97** [comment]
Hi,

For DPR, we used DPR-multi checkpoint (trained with multiple open-domain QA datasets), see link below: [DPR-multi](https://github.com/facebookresearch/DPR/blob/a31212dc0a54dfa85d8bfa01e1669f149ac832b7/dpr/data/download_data.py#L258)

For Contriver, we used the basic setting without fine-tuned on any QA dataset. 

```
from src.contriever import Contriever
contriever = Contriever.from_pretrained("facebook/contriever") 
```

Please kindly let me know if you have any other questions!

Best regards,
Wenhao

**Comment by Haelles** [comment]
> 

Thanks for your quick reply! However, I'm still confused with DPR. How did you use DPR-multi to select relevant passages in KILT knowledge source?  I wonder whether each passage('p1', 'p2' in the following block) of a wiki page is treated as a candidate. And the selected passages are directly put into FiD?

The format of KILT is as following:

```
{
 'wikipedia_title': 'Email marketing',
 'wikipedia_id': 1101759, 
 'text': ['p1', 'p2',...., 'pn'], # list of paragraph text
 'anchors': [{"text":,"href":,"paragraph_id":,"start":,"end":} ]  , 
 'categories': 'comma separated list of categories'
 'history': # some info from wikipedia, including original url
 'wikidata_info': # wikidata info
 }
```

**Comment by wyu97** [comment]
Yeah, each passage (p1, p2, ...) is treated as a candidate for retrieval. DPR-multi retrieves N candidates from the set of Wikipedia passages, then another reader model (text-davinci-002 under the zero-shot setting and FiD under the supervised setting) produces the final output.

**Comment by Haelles** [comment]
> Yeah, each passage (p1, p2, ...) is treated as a candidate for retrieval. DPR-multi retrieves N candidates from the set of Wikipedia passages, then another reader model (text-davinci-002 under the zero-shot setting and FiD under the supervised setting) produces the final output.

Thanks! I have one last question. Did you use hugging face to load DPR checkpoint and KILT, or modiy the original DPR repo and load KILT benchmark to retrieve?

**Comment by wyu97** [comment]
I used original DPR repo and load KILT benchmark to retrieve.

**Comment by Haelles** [comment]
> I used original DPR repo and load KILT benchmark to retrieve.

Thanks for your quick reply!
